### ISSUE TITLE
In-process detection

### ISSUE THREAD

**Issue by davidbrochart** [njsmith/perpetuo#3]
I was thinking that maybe the monitoring could be done in-process for tracking async tasks? For instance there could be a task that tries to run periodically and for each period reports the elapsed time, and if that time is (much) longer than the expected period, then the event loop is more than 100% busy.
But if a task is running without ever checkpointing, then this mechanism won't be able to detect it. Also, I'm not sure it can detect which task is blocking too long.

**Comment by njsmith** [comment]
Yeah, that would also be possible -- there are also a bunch of notes on that design here: https://github.com/python-trio/trio/issues/591

At work we've been having a lot of trouble with both GIL stalls and Trio stalls though, and GIL stalls are much harder to detect from within the process without interfering with the process, so that's why this exists :-)

**Comment by davidbrochart** [comment]
Thanks for the feedback and link!
